apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-configmap
  namespace: vault-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: vault
data:
  config.json: |
    {
    "listener": {
      "tcp":{
        "address": "0.0.0.0:8200",
        "tls_disable": 1,
        "tls_cert_file": "/etc/tls/vault.pem",
        "tls_key_file": "/etc/tls/vault-key.pem"
      }
    },
    "storage": {
      "consul": {
        "address": "consul:8500",
        "cluster_addr:" "http://vault-service.vault-system.svc.cluster.local:8201"
        "tls_skip_verify": 0,
        "tls_ca_file": "/etc/tls/consul/ca.pem",
        "tls_cert_file": "/etc/tls/consul/consul.pem",
        "tls_key_file": "/etc/tls/consul/consul-key.pem",
        "path": "vault/",
        "disable_registration": "false",
        "ha_enabled": "false",
        "token": "cae9343b-56d0-553d-b63b-dffb86a106bc"
      }
    },
    "ui": true
    "api_addr:" "http://vault-service.vault-system.svc.cluster.local:8200",
    "cluster_addr:" "http://vault-service.vault-system.svc.cluster.local:8201"
    }