## https://docs.projectcalico.org/networking/migrate-pools
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: k8s-ipv4-pool
spec:
  cidr: 10.0.0.0/16
  ipipMode: Always
  natOutgoing: true