apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-configmap
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: alertmanager
data:
  alertmanager.yml: |
    global: null
    receivers:
    - name: prometheus-msteams
      webhook_configs:
        - send_resolved: true
          url: http://prometheus-msteams.monitoring-system.svc.cluster.local:2000/decort-tech
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: prometheus-msteams
      repeat_interval: 3h