apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config 
  namespace: static-provisioner
data:
  storageClassMap: |     
    minio:
       hostDir: /minio/storage
       mountDir:  /minio/storage 
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2"
       volumeMode: Filesystem
       fsType: ext4
       namePattern: "*"