---
replicaCount: 1
image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.3.5

connectors:
# in alertmanager, this will be used as http://prometheus-msteams:2000/bar
- decort-tech: https://outlook.office.com/webhook/a3bb18bf-cf1d-483f-bb46-c99e3cddd98a@9efbb2a3-8e4f-4a4b-ae0b-e53fe5049a2a/IncomingWebhook/0a5e9959457a43a6a16810fee2432278/942bdb89-b89e-4b8d-a771-a9488addf015
container:
  additionalArgs:
    - -debug
