apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.6.0
        args:
        - --txt-owner-id=k8s
        - --provider=rfc2136
        - --rfc2136-host=10.10.1.10
        - --rfc2136-port=53
        - --rfc2136-zone=decort.tech
        - --rfc2136-tsig-axfr
        - --source=ingress
        - --domain-filter=decort.tech