apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring-system
data:
  datasource.yaml: |-
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring-system.svc.cluster.local:9090