apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: roel@decort.tech
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:  
    - selector:
        matchLabels:
          traefik2: "true"
        dnsZones:
          - "decort.tech"
      dns01:
        route53:
          region: eu-west-1
          accessKeyID: AKIAZOQYSZWYUCC5P5ML
          secretAccessKeySecretRef:
            name: cert-manager-route53
            key: secret-access-key
          #role: arn:aws:iam::649665367473:role/cert-manager