apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  namespace: unifi-controller
  labels:
    app: mongodb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb
  namespace: unifi-controller
  labels:
    app: mongodb
rules:
  - apiGroups: [""]
    resources:
      - pods
      - configmaps
      - secrets
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb
subjects:
  - kind: ServiceAccount
    name: mongodb
    namespace: unifi-controller