apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-configmap
  namespace: vault-system
  labels:
    app.kubernetes.io/name: consul
    app.kubernetes.io/component: vault-consul
data:
  myconfig.json: |
    {
      "ca_file": "/etc/tls/ca.pem",
      "cert_file": "/etc/tls/consul.pem",
      "key_file": "/etc/tls/consul-key.pem",
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "ports": {
        "https": 8443
      },
      "acl": {
        "enabled": true,
        "default_policy": "deny",
        "down_policy": "extend-cache"
     },
     "primary_datacenter": "nldc01"
    }